name: Deploy to bmc-00.github.io

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때 실행 (원하는 브랜치로 바꿔도 됨)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 2) Node 셋업
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20  # 또는 18, 20 등 원하는 버전

      # 3) 종속성 설치 & 빌드
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 4) bmc-00.github.io 레포 클론
      - name: Clone bmc-00.github.io
        run: |
          git clone --depth=1 https://github.com/bmc-00/bmc-00.github.io.git out
        shell: bash

      # 5) 빌드 결과물 dist -> out 폴더에 복사
      - name: Copy dist to out
        run: |
          rm -rf out/*
          cp -r dist/* out/

      # 6) out 폴더에 커밋 & 푸시
      - name: Commit and Push to bmc-00.github.io
        run: |
          cd out
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy from b-log_frontend commit: ${{ github.sha }}"
          git push
        env:
          # 깃푸시 권한을 위해서, HTTPS URL로 인증하도록 user:token 형식 사용
          # https://username:token@github.com/...
          GIT_HTTP_USER: ${{ github.actor }}
          GIT_HTTP_PASSWORD: ${{ secrets.DEPLOY_TOKEN }}
